DROP TABLE IF EXISTS NOMBRETABLA;

--Ejemplo de crear tabla, modificar segun sea necesario
CREATE TABLE NOMBRETABLA(ID LONG AUTO_INCREMENT PRIMARY KEY, CODIGO INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL,
             LABORATORIO VARCHAR(50) NOT NULL, CANTIDAD INT NOT NULL, PRECIO NUMERIC(10, 2) NOT NULL)